import { describe, it, expect } from 'vitest';
import { createApiRoutes, type ApiRoutesDeps } from './routes.js';

function deps(): ApiRoutesDeps {
  const empty = {} as never;
  return {
    features: empty,
    admin: empty,
    launcher: empty,
    resolver: empty,
    factory: empty,
    sessionConfig: empty,
    sessions: empty,
    providers: empty,
    aggregates: empty,
    summarizer: empty,
    summaries: empty,
    workSummaries: empty,
    sessionFiles: empty,
    sessionSummaries: empty,
    imports: empty,
    skills: empty,
    sessionBootstrap: empty,
    tasks: empty,
    ideUsage: empty,
    configRegistry: empty,
    currentConfig: {},
    configSecretPaths: [],
    agencyStatus: () => ({ installed: true }),
    githubStatus: () => Promise.resolve({ authenticated: true, login: 'x' }),
    githubSignInStart: () =>
      Promise.resolve({
        userCode: 'X',
        verificationUri: 'u',
        deviceCode: 'd',
        interval: 5,
        expiresIn: 900,
      }),
    githubSignInPoll: () => Promise.resolve({ status: 'success' as const }),
    azureStatus: () =>
      Promise.resolve({ authenticated: true, account: 'x', message: null }),
    azureSignIn: () =>
      Promise.resolve({ authenticated: true, account: 'x', message: null }),
    repos: empty,
    repositoryContexts: empty,
    provisionRepo: () => Promise.resolve(empty),
    listGithubRepos: () => Promise.resolve([]),
    listAzureRepos: () => Promise.resolve([]),
    prFeatures: empty,
    prReviews: empty,
    logger: empty,
  };
}

describe('createApiRoutes', () => {
  it('assembles the full route table from every controller', () => {
    const routes = createApiRoutes(deps());
    const signatures = routes.map((r) => `${r.method} ${r.path}`);
    expect(signatures).toEqual([
      'post /features',
      'get /features',
      'get /features/:id',
      'put /features/:id',
      'delete /features/:id',
      'post /features/:featureId/sessions',
      'get /features/:featureId/sessions',
      'get /sessions/:id',
      'put /sessions/:id',
      'delete /sessions/:id',
      'post /features/:featureId/terminal-sessions',
      'get /providers',
      'get /providers/:id/models',
      'get /features/:featureId/usage',
      'get /usage/totals',
      'get /usage/workspace',
      'post /features/:featureId/summary',
      'get /features/:featureId/summary',
      'get /features/:featureId/work-summary',
      'get /sessions/:sessionId/files',
      'post /features/:featureId/sessions/:sessionId/summary',
      'get /features/:featureId/sessions/:sessionId/summary',
      'get /importable-sessions',
      'post /features/:featureId/import-session',
      'get /skills/export',
      'post /skills/import',
      'get /skills',
      'post /skills',
      'get /skills/:id/export',
      'get /skills/:id',
      'put /skills/:id',
      'delete /skills/:id',
      'post /skills/:id/attachments',
      'delete /skills/attachments/:attachmentId',
      'get /features/:featureId/skills',
      'get /sessions/:sessionId/skills',
      'get /features/:featureId/tasks',
      'post /features/:featureId/tasks/generate',
      'post /features/:featureId/tasks',
      'put /tasks/:taskId',
      'delete /tasks/:taskId',
      'get /features/:featureId/pr-review',
      'post /features/:featureId/pr-review/refresh',
      'get /usage/ide',
      'get /config',
      'get /agency/status',
      'get /github/status',
      'post /github/signin/start',
      'post /github/signin/poll',
      'get /azure-devops/status',
      'post /azure-devops/signin',
      'get /repos',
      'post /repos',
      'get /repos/:id/context',
      'post /repos/:id/context/refresh',
      'delete /repos/:id',
      'get /providers/github/repos',
      'get /providers/azure-devops/repos',
      'get /repos/:id/pulls',
      'post /repos/:id/pulls',
    ]);
  });
});
