import { describe, it, expect } from 'vitest';
import { createApiRoutes, type ApiRoutesDeps } from './routes.js';

function deps(): ApiRoutesDeps {
  const empty = {} as never;
  return {
    features: empty,
    admin: empty,
    launcher: empty,
    resolver: empty,
    factory: empty,
    sessionConfig: empty,
    sessions: empty,
    sessionHistory: empty,
    providers: empty,
    aggregates: empty,
    summarizer: empty,
    summaries: empty,
    workSummaries: empty,
    sessionFiles: empty,
    sessionSummaries: empty,
    imports: empty,
    skills: empty,
    sessionBootstrap: empty,
    tasks: empty,
    tree: empty,
    ideUsage: empty,
    usageDetail: empty,
    mcp: empty,
    configRegistry: empty,
    currentConfig: {},
    configSecretPaths: [],
    configOverrides: empty,
    agencyStatus: () => ({ installed: true }),
    githubStatus: () => Promise.resolve({ authenticated: true, login: 'x' }),
    githubSignInStart: () =>
      Promise.resolve({
        userCode: 'X',
        verificationUri: 'u',
        deviceCode: 'd',
        interval: 5,
        expiresIn: 900,
      }),
    githubSignInPoll: () => Promise.resolve({ status: 'success' as const }),
    githubSignOut: () =>
      Promise.resolve({ authenticated: false, login: null }),
    azureStatus: () =>
      Promise.resolve({ authenticated: true, account: 'x', message: null }),
    azureSignIn: () =>
      Promise.resolve({ authenticated: true, account: 'x', message: null }),
    repos: empty,
    repositoryContexts: empty,
    repoInsights: empty,
    provisionRepo: () => Promise.resolve(empty),
    listGithubRepos: () => Promise.resolve([]),
    listAzureRepos: () => Promise.resolve([]),
    prFeatures: empty,
    prReviews: empty,
    reviewBoard: empty,
    prComments: empty,
    prApprovals: empty,
    prDescriptions: empty,
    worktrees: empty,
    context: empty,
    automations: empty,
    subagents: empty,
    logger: empty,
  };
}

describe('createApiRoutes', () => {
  it('assembles the full route table from every controller', () => {
    const routes = createApiRoutes(deps());
    const signatures = routes.map((r) => `${r.method} ${r.path}`);
    expect(signatures).toEqual([
      'get /health',
      'post /features',
      'get /features',
      'get /features/:id',
      'put /features/:id',
      'post /features/:id/move',
      'delete /features/:id',
      'post /features/:featureId/sessions',
      'get /features/:featureId/sessions',
      'get /sessions/:id',
      'put /sessions/:id',
      'delete /sessions/:id',
      'post /features/:featureId/terminal-sessions',
      'get /providers',
      'get /providers/:id/models',
      'get /mcp/providers',
      'get /mcp/providers/:providerId/servers',
      'put /mcp/providers/:providerId/servers',
      'put /mcp/providers/:providerId/servers/:serverName/tools/:toolName',
      'post /mcp/providers/:providerId/servers/:serverName/restart',
      'get /features/:featureId/usage',
      'get /usage/totals',
      'get /usage/workspace',
      'get /sessions/:sessionId/usage',
      'get /features/:featureId/usage/events',
      'get /repos/:repoId/usage/events',
      'post /features/:featureId/summary',
      'get /features/:featureId/summary',
      'get /features/:featureId/work-summary',
      'get /sessions/:sessionId/files',
      'post /features/:featureId/sessions/:sessionId/summary',
      'get /features/:featureId/sessions/:sessionId/summary',
      'get /importable-sessions',
      'post /features/:featureId/import-session',
      'get /skills/export',
      'post /skills/import',
      'get /skills',
      'post /skills',
      'get /skills/:id/export',
      'get /skills/:id',
      'put /skills/:id',
      'delete /skills/:id',
      'post /skills/:id/attachments',
      'delete /skills/attachments/:attachmentId',
      'get /features/:featureId/skills',
      'get /sessions/:sessionId/skills',
      'get /features/:featureId/tasks',
      'post /features/:featureId/tasks/generate',
      'post /features/:featureId/tasks',
      'put /tasks/:taskId',
      'delete /tasks/:taskId',
      'get /features/:featureId/groups',
      'post /features/:featureId/groups',
      'put /groups/:groupId',
      'delete /groups/:groupId',
      'post /tree/move',
      'get /features/:featureId/pr-review',
      'post /features/:featureId/pr-review/refresh',
      'post /features/:featureId/pr-review/steps/:step/retry',
      'post /features/:featureId/pr-review/files/explain',
      'post /features/:featureId/pr-review/graph-chat',
      'post /features/:featureId/pr-review/approve',
      'post /features/:featureId/pr-review/export-description',
      'get /features/:featureId/pr-review/comments',
      'post /features/:featureId/pr-review/comments',
      'post /features/:featureId/pr-review/comments/:threadId/status',
      'get /features/:featureId/review-board',
      'post /features/:featureId/review-board/analyze',
      'post /features/:featureId/review-board/perspectives/:perspectiveId/analyze',
      'post /features/:featureId/review-board/chat',
      'get /worktrees',
      'post /worktrees/remove',
      'get /usage/ide',
      'get /context/:scope',
      'put /context/:scope',
      'post /context/:scope/remember',
      'get /automations',
      'get /automations/:id',
      'post /automations',
      'post /automations/:id/progress',
      'post /automations/:id/planned-steps',
      'post /automations/:id/subagents',
      'post /automations/:id/pause',
      'post /automations/:id/resume',
      'post /automations/:id/cancel',
      'post /automations/:id/run',
      'post /subagents/:id/progress',
      'post /subagents/:id/complete',
      'post /subagents/:id/fail',
      'delete /automations/:id',
      'get /config',
      'put /config/:namespace',
      'delete /config/:namespace',
      'get /agency/status',
      'get /github/status',
      'post /github/signin/start',
      'post /github/signin/poll',
      'post /github/signout',
      'get /azure-devops/status',
      'post /azure-devops/signin',
      'get /repos',
      'post /repos',
      'get /repos/:id/context',
      'get /repos/:id/insights',
      'get /repos/:id/insights/file',
      'post /repos/:id/context/refresh',
      'delete /repos/:id',
      'get /providers/github/repos',
      'get /providers/azure-devops/repos',
      'get /repos/:id/pulls',
      'post /repos/:id/pulls',
    ]);
  });
});
